EmprestimoLivros/Models/EmprestimosModel.cs
using System.ComponentModel.DataAnnotations;

namespace EmprestimoLivros.Models
{
    public class EmprestimosModel
    {
        public int Id { get; set; }
        public string Recebedor { get; set; }
        [Required(ErrorMessage = "Digite o nome do Recebedor!")]
        public string Fornecedor { get; set; }
        [Required(ErrorMessage = "Digite o nome do Fornecedor!")]
        public string LivroEmprestado { get; set; }
        [Required(ErrorMessage = "Digite o nome do Livro!")]
        public DateTime DataEmprestimo { get; set; }

    }
}

EmprestimoLivros/Models/ErrorViewModel.cs
namespace EmprestimoLivros.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

EmprestimoLivros/Controllers/EmprestimoController.cs
using ClosedXML.Excel;
using EmprestimoLivros.Data;
using EmprestimoLivros.Models;
using Microsoft.AspNetCore.Mvc;
using System.Data;


namespace EmprestimosBase.Controllers
{
    public class EmprestimoController : Controller
    {
        readonly private ApplicationDbContext _db;

        public EmprestimoController(ApplicationDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            IEnumerable<EmprestimosModel> emprestimos = _db.Emprestimos;
            return View(emprestimos);
        }

        [HttpGet]
        public IActionResult Cadastrar()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Editar(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            EmprestimosModel emprestimo = _db.Emprestimos.FirstOrDefault(x => x.Id == id);

            if (emprestimo == null)
            {
                return NotFound();
            }

            return View(emprestimo);
        }

        [HttpGet]
        public IActionResult Excluir(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            EmprestimosModel emprestimo = _db.Emprestimos.FirstOrDefault(x => x.Id == id);

            if (emprestimo == null)
            {
                return NotFound();
            }

            return View(emprestimo);
        }

        [HttpPost]
        public IActionResult Cadastrar(EmprestimosModel emprestimos)
        {
            if (ModelState.IsValid)
            {
                _db.Emprestimos.Add(emprestimos);
                _db.SaveChanges();

                TempData["MensagemSucesso"] = "Cadastro realizado com sucesso!";

                return RedirectToAction("Index");
            }
            return View();
        }

        [HttpPost]
        public IActionResult Editar(EmprestimosModel emprestimos)
        {
            if (ModelState.IsValid)
            {
                var emprestimoDB = _db.Emprestimos.Find(emprestimos.Id);

                emprestimoDB.LivroEmprestado = emprestimos.LivroEmprestado;
                emprestimoDB.Recebedor = emprestimos.Recebedor;
                emprestimoDB.Fornecedor = emprestimos.Fornecedor;

                _db.Emprestimos.Update(emprestimoDB);
                _db.SaveChanges();

                TempData["MensagemSucesso"] = "Edição realizado com sucesso!";

                return RedirectToAction("Index");
            }

            TempData["MensagemErro"] = "Ocorreu algum erro no momento da edição!";
            return View(emprestimos);
        }

        [HttpPost]
        public IActionResult Excluir(EmprestimosModel emprestimos)
        {
            if (emprestimos == null)
            {
                return NotFound();
            }

            _db.Emprestimos.Remove(emprestimos);
            _db.SaveChanges();

            TempData["MensagemSucesso"] = "Exclusão realizado com sucesso!";

            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Exportar()
        {
            var dados = GetDados();

            using (XLWorkbook workBook = new XLWorkbook())
            {
                workBook.AddWorksheet(dados, "Dados Empréstimos");
                using (MemoryStream ms = new MemoryStream())
                {
                    workBook.SaveAs(ms);
                    return File(ms.ToArray(), "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "Emprestimo.xls");
                }

            }
        }

        private DataTable GetDados()
        {
            DataTable dataTable = new DataTable();

            dataTable.TableName = "Dados emprestimos";

            dataTable.Columns.Add("Recebedor", typeof(string));
            dataTable.Columns.Add("Fornecedor", typeof(string));
            dataTable.Columns.Add("Livro", typeof(string));
            dataTable.Columns.Add("Data última atualização", typeof(DateTime));

            var dados = _db.Emprestimos.ToList();

            if (dados.Count > 0)
            {
                dados.ForEach(emprestimo =>
                {
                    dataTable.Rows.Add(emprestimo.Recebedor, emprestimo.Fornecedor, emprestimo.LivroEmprestado, emprestimo.DataEmprestimo);
                });
            }

            return dataTable;

        }
    }
}

EmprestimoLivros/Controllers/HomeController.cs
using EmprestimoLivros.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace EmprestimoLivros.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

EmprestimoLivros/Views/Emprestimo/Cadastrar.cshtml
@model EmprestimosModel
@{
    ViewData["title"] = "Cadastrar Empréstimo";
}

<div class="container bg-white p-5 rounded-5 text-dark">
    <div class="mb-5 text-center">
        <h1>Cadastro de Empréstimos</h1>
    </div>

    <form method="post" asp-controller="Emprestimo" asp-action="Cadastrar">
        <div class="mb-3">
            <label for="Recebedor" class="form-label">Recebedor:</label>
            <input type="text" asp-for="Recebedor" class="shadow-none form-control" id="exampleInputRecebedor" placeholder="Quem está recebendo o livro?">
        </div>
        <div class="mb-3">
            <label for="Fornecedor" class="form-label">Fornecedor:</label>
            <input asp-for="Fornecedor" type="text" class="form-control shadow-none" id="exampleInputFornecedor" placeholder="Quem está emprestando o livro?">
        </div>
        <div class="mb-3">
            <label class="form-label" for="LivroEmprestado">Livro:</label>
            <input type="text" asp-for="LivroEmprestado" class="form-control shadow-none" id="exampleInputLivroEmprestado" placeholder="Qual livro está sendo emprestado?">
        </div>
        <div class="d-flex gap-5 mt-5">
            <button type="submit" class="btn btn-success w-50">Adicionar</button>
            <a class="btn btn-primary w-50" asp-controller="Emprestimo" asp-action="Index">Voltar</a>
        </div>
    </form>
</div>

EmprestimoLivros/Views/Emprestimo/Editar.cshtml
@model EmprestimosModel
@{
    ViewData["title"] = "Editar empréstimo";
}



<div class="container bg-dark p-5 rounded-5">
    <div class="mb-5 text-center">
        <h1 class="text-light">Edição de Empréstimos</h1>
    </div>
    <form method="post" asp-controller="Emprestimo" asp-action="Editar">
        <input type="hidden" asp-for=Id />
        <div class="mb-3">
            <label for="Recebedor" class="form-label text-light">Recebedor:</label>
            <input type="text" asp-for="Recebedor" class="shadow-none form-control" id="exampleInputRecebedor" placeholder="Quem está recebendo o livro?">
        </div>
        <div class="mb-3">
            <label for="Fornecedor" class="form-label text-light">Fornecedor:</label>
            <input asp-for="Fornecedor" type="text" class="shadow-none form-control" id="exampleInputFornecedor" placeholder="Quem está emprestando o livro?">
        </div>
        <div class="mb-3">
            <label class="form-label text-light" for="LivroEmprestado">Livro:</label>
            <input type="text" asp-for="LivroEmprestado" class="shadow-none form-control" id="exampleInputLivroEmprestado" placeholder="Qual livro está sendo emprestado?">
        </div>
        <div class="d-flex gap-5 mt-5">
            <button type="submit" class="w-50 btn btn-success">Editar</button>
            <a class="w-50 btn btn-primary" asp-controller="Emprestimo" asp-action="Index">Voltar</a>
        </div>
    </form>
</div>

EmprestimoLivros/Views/Emprestimo/Excluir.cshtml
@model EmprestimosModel
@{
    TempData["title"] = "Excluir empréstimos";
}

<div class="container bg-dark p-5 rounded-5">
    <div class="mb-5 text-center">
        <h1 class="text-light">Exclusão de Empréstimos</h1>
    </div>

    <form method="post" asp-controller="Emprestimo" asp-action="Excluir">
        <input type="hidden" asp-for=Id />
        <h2 class="text-light form-label">Tem certeza que deseja excluir o registro abaixo?</h2>

        <div class="mb-3">
            <label for="Recebedor" class="text-light form-label">Recebedor:</label>
            <input type="text" asp-for="Recebedor" class="shadow-none form-control text-dark" id="exampleInputRecebedor" placeholder="Quem está recebendo o livro?" disabled>
        </div>

        <div class="mb-3">
            <label for="Fornecedor" class="text-light form-label">Fornecedor:</label>
            <input asp-for="Fornecedor" type="text" class="shadow-none form-control text-dark" id="exampleInputFornecedor" placeholder="Quem está emprestando o livro?" disabled>
        </div>

        <div class="mb-3">
            <label class="text-light form-label" for="LivroEmprestado">Livro:</label>
            <input type="text" asp-for="LivroEmprestado" class="shadow-none form-control text-dark" id="exampleInputLivroEmprestado" placeholder="Qual livro está sendo emprestado?" disabled>
        </div>

        <div class="d-flex gap-5 mt-5">
            <button type="submit" class="w-50 btn btn-danger">Excluir</button>
            <a class="w-50 btn btn-primary" asp-controller="Emprestimo" asp-action="Index">Voltar</a>
        </div>
    </form>
</div>

EmprestimoLivros/Views/Emprestimo/Index.cshtml
@model IEnumerable<EmprestimosModel>

@{
    ViewData["title"] = "Empréstimos";
}

<div class="container ">
    <table class="table table-dark table-hover">

        <div class="d-flex justify-content-between align-items-center mb-5">
            <h1>Empréstimos</h1>

            <div>
                <a class="btn btn-success mx-2" asp-controller="Emprestimo" asp-action="Exportar"><i class="bi bi-file-earmark-plus mx-2"></i>Exportar</a>
                <a class="btn btn-success mx-2" asp-controller="Emprestimo" asp-action="Cadastrar"><i class="bi bi-person-plus  mx-2"></i></i>Cadastrar novo empréstimo</a>
            </div>
        </div>

        @if (TempData["MensagemSucesso"] != null)
        {
            <div class="alert alert-success text-light" role="alert">
                @TempData["MensagemSucesso"]
            </div>
        }

        @if (TempData["MensagemErro"] != null)
        {
            <div class="alert alert-danger text-light" role="alert">
                @TempData["MensagemErro"]
            </div>
        }


        <table id="Emprestimos" class="table table-light table-hover mt-5">
            <br />
            <thead>
                <tr>
                    <th scope="col">Recebedor</th>
                    <th scope="col">Fornecedor</th>
                    <th scope="col">Livro</th>
                    <th scope="col">Data empréstimo</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>

                @if (Model != null)
                {
                    @foreach (var emprestimo in Model)
                    {
                        <tr>
                            <th scope="row">@emprestimo.Recebedor</th>
                            <td>@emprestimo.Fornecedor</td>
                            <td>@emprestimo.LivroEmprestado</td>
                            <td>@emprestimo.DataEmprestimo</td>
                            <td>
                                <a class="btn btn-warning mx-2" asp-controller="Emprestimo" asp-action="Editar" asp-route-id="@emprestimo.Id"><i class="bi bi-pencil-square"></i>Editar</a>
                                <a class="btn btn-danger mx-2" asp-controller="Emprestimo" asp-action="Excluir" asp-route-id="@emprestimo.Id"><i class="bi bi-trash3-fill"></i>Excluir</a>
                            </td>
                        </tr>
                    }
                }

            </tbody>
        </table>
    </table>
</div>

<footer class="border-top footer text-muted bg-dark">
    <div class="container">
        &copy; 2024 - Empréstimos Devti.Tech - <a asp-area="" asp-controller="Emprestimo" asp-action="Index" class="text-light">Empréstimos</a>
    </div>
</footer>

EmprestimoLivros/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Conexão Literária</h1>
    <p>Explorando Mundos, Página por Página: Sua Aventura Literária Começa Aqui!</p>
    <div>
        <img src="/img/livro.jpg"/>
    </div>
</div>

EmprestimoLivros/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EmprestimoLivros</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/Sketchy.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/EmprestimoLivros.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link href="https://cdn.datatables.net/v/dt/dt-1.13.8/datatables.min.css" rel="stylesheet">

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-dark border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" text-light" asp-area="" asp-controller="Home" asp-action="Index">EmprestimoLivros</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index"><i class="bi bi-house-fill mx-2"></i>Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Emprestimo" asp-action="Index"><i class="bi bi-journals mx-2"></i>Empréstimos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

   
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.datatables.net/v/dt/dt-1.13.8/datatables.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>